### ISSUE TITLE
Add to watch list from "what to watch"

### ISSUE THREAD

**Issue by cdierkens** [dierkens-dev/basement-of-stinkology#274]
- Add a plus button to the bottom right of the screen
- Clicking it brings up the same search box as the "Watch List" page
- When the movie is added, it is added to current users "Watch List"

**Comment by sonofab1rd** [comment]
started on this:
need to make /users/me/watch-list/add-movie.vue into a component that can be used on any page
started by copying add-movie into movie/what-to-watch/add-movie

This error when adding movie

Invalid `prisma.userWatchListMovie.upsert()` invocation in
/Users/jacobdierkens/Projects/basement-of-stinkology/src/server/api/users/me/watch-list.post.ts:31:1

  28   });
  29 }
  30 
→ 31 const userWatchListMovie = await prisma.userWatchListMovie.upsert({
       where: {
         userId_movieId: {
         ~~~~~~~~~~~~~~
           userId: "239ea8d3-5981-4e2b-be4b-d855d7356281",
           movieId: "a273d5f3-c465-4a53-8465-4b7833d44bbf"
         },
     ?   id?: String,
     ?   AND?: UserWatchListMovieWhereInput | UserWatchListMovieWhereInput[],
     ?   OR?: UserWatchListMovieWhereInput[],
     ?   NOT?: UserWatchListMovieWhereInput | UserWatchListMovieWhereInput[],
     ?   userId?: UuidFilter | String,
     ?   movieId?: UuidFilter | String,
     ?   user?: UserRelationFilter | UserWhereInput,
     ?   movie?: MovieRelationFilter | MovieWhereInput
       },
       update: {},
       create: {
         userId: "239ea8d3-5981-4e2b-be4b-d855d7356281",
         movieId: "a273d5f3-c465-4a53-8465-4b7833d44bbf"
       },
       select: {
         movie: {
           select: {
             id: true,
             title: true,
             releaseDate: true,
             tagline: true,
             overview: true,
             poster: true
           }
         }
       }
     })

Unknown argument `userId_movieId`. Available options are marked with ?.
  at En (./node_modules/@prisma/client/runtime/library.js:116:5888)  
  at Cn.handleRequestError (./node_modules/@prisma/client/runtime/library.js:123:6516)  
  at Cn.handleAndLogRequestError (./node_modules/@prisma/client/runtime/library.js:123:6206)  
  at Cn.request (./node_modules/@prisma/client/runtime/library.js:123:5926)  
  at async l (./node_modules/@prisma/client/runtime/library.js:128:9968)  
  at <anonymous> (./src/server/api/users/me/watch-list.post.ts:31:1)  
  at <anonymous> (./src/server/utils/validated-handler.server.ts:27:1)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1630:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1840:7)
